services:
  app:
    image: akinaksoy/repsy-package-manager:latest
    container_name: repsy-api
    depends_on:
      - postgres
      - minio
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/repsy
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=2546
      - STORAGE_STRATEGY=file-system # Options: file-system, object-storage
      - STORAGE_FILESYSTEM_BASE_PATH=/app/storage
      - STORAGE_OBJECT_ENDPOINT=http://minio:9000
      - STORAGE_OBJECT_ACCESS_KEY=minioadmin
      - STORAGE_OBJECT_SECRET_KEY=minioadmin
      - STORAGE_OBJECT_BUCKET_NAME=repsy
    ports:
      - "8080:8080"
    volumes:
      - ./storage:/app/storage
    networks:
      - repsy-network

  postgres:
    image: postgres:17-alpine
    container_name: repsy-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2546
      - POSTGRES_DB=repsy
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - repsy-network

  minio:
    image: minio/minio:latest
    container_name: repsy-minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    networks:
      - repsy-network

volumes:
  postgres-data:
  minio-data:

networks:
  repsy-network:
    driver: bridge